#Réalisé par Ivann LARUELLE / ivann.laruelle@utt.fr
---
Ubuntu_DNSResolverServiceOnHost: "systemd-resolved.service"
RHELCent_networkCard: "eth0"

nsd_vars:
  logfile: "/var/log/nsd.log"
  pidfile: "/run/nsd/nsd.pid"
  hideversion: "yes"

DNNSEC_keys:
  algorithm: "RSASHA1-NSEC3-SHA1"
  size: "2048"

nameservers:
  - "8.8.8.8"
  - "8.8.4.4"

DebianUbuntu_CommonPackages:
  - nano
  - gawk
  - dnsutils
  - net-tools
  - nsd

RHELCent_CommonPackages:
  - epel-release
  - gawk
  - bind-utils
  - net-tools
  - nsd

DebianUbuntu_MasterPackages:
  - haveged
  - ldnsutils

RHELCent_MasterPackages:
  - haveged
  - ldns