#Réalisé par Ivann LARUELLE / ivann.laruelle@utt.fr
---
  - set_fact:
      item.domain: "{{ item.FullyQualifiedDomainName[:-1] }}"
    loop: "{{ domains }}"

  - name: Creation de l'utilisateur nsd
    user:
      name: nsd
      system: yes
  
  - name: Changement DNS
    copy:
      src: files/nodnsupdate
      dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
      owner: root
      mode: "711"

  - copy:
      src: files/resolv.conf
      dest: /etc/resolv.conf
      backup: yes
    
  - service:
      name: "{{ DNSResolverServiceOnHost }}"
      state: restarted
      enabled: yes

  - name: Installation d'outils de base
    package: 
      name: "{{ item }}"
      state: latest
    with_items:
      - nano
      - dnsutils
      - net-tools
      - nsd

  - file:
      path: /etc/nsd/zones
      state: directory
      owner: nsd
      mode: "710"
    when: not ansible_check_mode