#Réalisé par Ivann LARUELLE / ivann.laruelle@utt.fr
---
  - name: Creation de l'utilisateur nsd
    user:
      name: nsd
      system: yes

  - name: Arret du service DNS local
    service:
      name: "{{ DNSResolverServiceOnHost }}"
      state: stopped
      enabled: no

  - name: Blocage de la mise à jour auto des IP DNS resolver
    copy:
      src: files/nodnsupdate
      dest: /etc/dhcp/dhclient-enter-hooks.d/nodnsupdate
      owner: root
      mode: "711"

  - name: Utilisation des DNS personnalisés
    template:
      src: resolv.conf
      dest: /etc/resolv.conf
      backup: yes

  - name: Installation d'outils de base
    package: 
      name: "{{ item }}"
      state: latest
    with_items:
      - nano
      - dnsutils
      - net-tools
      - nsd

  - file:
      path: /etc/nsd/zones
      state: directory
      owner: nsd
      mode: "710"
    when: not ansible_check_mode