#Réalisé par Ivann LARUELLE / ivann.laruelle@utt.fr
---
  - shell: cat /etc/nsd/zones/{{ item.domain }}/zsk
    register: zsk

  - shell: cat /etc/nsd/zones/{{ item.domain }}/ksk 
    register: ksk

  - name: Signature de la zone de {{ item.domain }}
    shell: ldns-signzone -n -p -s $(head -n 1000 /dev/urandom | sha1sum | cut -b 1-16) -f /etc/nsd/zones/{{ item.domain }}.zone.signed /etc/nsd/zones/{{ item.domain }}.zone {{ zsk.stdout }} {{ ksk.stdout }}
    args: 
      chdir: /etc/nsd/zones
    when: not ansible_check_mode

  - file:
      path: /etc/nsd/zones/{{ item.domain }}
      owner: nsd
      mode: "700"
    when: not ansible_check_mode

  - shell: ldns-key2ds -n -{{ mode }} {{ item.domain }}.zone.signed
    args: 
      chdir: /etc/nsd/zones
    register: DSKeys
    when: not ansible_check_mode
    loop:
      - '1'
      - '2'
      - 'g'
      - '4'
    loop_control:
      loop_var: mode
    ignore_errors: yes

  - name: Récupération des clefs DS {{ item.domain }}
    debug: 
      msg: 
        - "SHA1   : {{ DSKeys.results[0].stdout }}"
        - "SHA256 : {{ DSKeys.results[1].stdout }}"
        - "GOST   : {{ DSKeys.results[2].stdout }}"
        - "SHA384 : {{ DSKeys.results[3].stdout }}"
    when: not ansible_check_mode