---
DNSTransferKey: h9k6FhsI8AH2E4+OlKS6cVtGZdXoRDr9

IPDNSSlave: "{{ hostvars['dnsslave']['ansible_facts'][default_ipv4][address] }}"
IPDNSMaster: "{{ hostvars['dnsmaster']['ansible_facts'][default_ipv4][address] }}"

domains:
  - FQDN: uttnetgroup.fr.
    masterDNServerName: hostmaster.uttnetgroup.fr.
    defaultTTL: 1h
    SOA:
      mailSOAFormat: hostmaster.uttnetgroup.fr.
      refresh: 86400
      retry: 7200
      expire: 604800
      ttl: 300
    records:
    - name: hostmaster.uttnetgroup.fr.
      ttl: 300
      type: A
      data: 10.0.1.2
    - name: mdr.uttnetgroup.fr.
      ttl: 6300
      class: IN
      type: CNAME
      data: lol.utt.fr
    - name: jpp
      type: A
      data: 100.25.5.6
  - FQDN: up.fr.
    masterDNServerName: jkehfjkezf.up.fr.
    defaultTTL: 1h
    SOA:
      mailSOAFormat: hostmaster.up.fr.
      refresh: 86400
      retry: 7200
      expire: 604800
      ttl: 300
    records:
    - name: jkehfjkezf.up.fr.
      ttl: 300
      class: IN
      type: A
      data: 10.5.1.2
    - name: mdr.up.fr.
      ttl: 6300
      class: IN
      type: CNAME
      data: lol.ejhh.fr