#
# Author : Ivann LARUELLE / ivann.laruelle@gmail.com / @ILaruelle
# Github (larueli) : https://github.com/larueli/ansible-nsd-role/
#
---
  - shell: cat /etc/nsd/keys/{{ item.FQDN }}/zsk
    register: zsk

  - shell: cat /etc/nsd/keys/{{ item.FQDN }}/ksk 
    register: ksk

  - name: Signature de la zone de {{ item.FQDN[:-1] }}
    shell: ldns-signzone -n -p -s $(head -n 1000 /dev/urandom | sha1sum | cut -b 1-16) -f /etc/nsd/zones/{{ item.FQDN }}zone.signed /etc/nsd/zones/{{ item.FQDN }}zone {{ zsk.stdout }} {{ ksk.stdout }}
    args: 
      chdir: /etc/nsd/keys/{{ item.FQDN }}
    when: not ansible_check_mode

  - file:
      path: /etc/nsd/zones/{{ item.FQDN }}zone.signed
      owner: nsd
      mode: "600"
    when: not ansible_check_mode

  - shell: ldns-key2ds -n -{{ mode }} {{ item.FQDN }}zone.signed
    args: 
      chdir: /etc/nsd/zones
    register: DSKeys
    when: not ansible_check_mode
    loop:
      - '1'
      - '2'
      - 'g'
      - '4'
    loop_control:
      loop_var: mode
    ignore_errors: yes

  - name: Récupération des clefs DS {{ item.FQDN[:-1] }}
    debug: 
      msg: 
        - "SHA1   : {{ DSKeys.results[0].stdout }}"
        - "SHA256 : {{ DSKeys.results[1].stdout }}"
        - "GOST   : {{ DSKeys.results[2].stdout }}"
        - "SHA384 : {{ DSKeys.results[3].stdout }}"
    when: not ansible_check_mode

  - shell: cat /etc/nsd/keys/{{ item.FQDN }}/$(/etc/nsd/keys/{{ ksk.stdout }}.private
    register: kskprivate
  - name: Affichage de clef privée KSK {{ item.FQDN[:-1] }}
    debug:
      var: kskprivate.stdout 

  - shell: cat /etc/nsd/keys/{{ item.FQDN }}/{{ ksk.stdout }}.key
    register: kskpublic
  - name: Affichage de clef privée KSK {{ item.FQDN[:-1] }}
    debug:
      var: kskpublic.stdout 