#Réalisé par Ivann LARUELLE / ivann.laruelle@utt.fr
---
  - hosts:
      - dns
    gather_facts: yes
    remote_user: root
    tasks: []

  - hosts:
      - dns
    gather_facts: yes
    serial: 1
    remote_user: root
    tasks:
      - debug:
          var: hostvars['dnsslave']['ansible_facts']['default_ipv4']['address']
