#Réalisé par Ivann LARUELLE / ivann.laruelle@utt.fr
---
IPDNSSlave: "{{ groups['dns_slave'][0] }}"
IPDNSMaster: "{{ groups['dns_master'][0] }}"

nsd_vars:
  logfile: "/var/log/nsd.log"
  pidfile: "/run/nsd/nsd.pid"
  hideversion: "yes"

DNNSEC_keys:
  algorithm: "RSASHA1-NSEC3-SHA1"
  size: "2048"