#
# Author : Ivann LARUELLE / ivann.laruelle@gmail.com / @ILaruelle
# Github (larueli) : https://github.com/larueli/ansible-nsd-role/
#
---
  - name: Installation de python 3
    package:
      name: python3
      state: latest

  - name: Installation de la clef SSH
    authorized_key: 
      user: root
      exclusive: no
      key: "{{ lookup('file','{{ pathToSSHKey }}') }}"